<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>vcrunner-broker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CtrlX.OpCon.Runner.Core\CtrlX.OpCon.Runner.Core.csproj" />
  </ItemGroup>

</Project>
